# Generated by Django 6.0.1 on 2026-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestone',
            name='status',
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
