# Generated by Django 6.0.1 on 2026-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_projectmilestone_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
