# Generated by Django 6.0.1 on 2026-01-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
