# Generated by Django 6.0.1 on 2026-01-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_project_projectmilestone_projectmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
