# Generated by Django 6.0.1 on 2026-02-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_task_taskprogress_taskassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprogress',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
