# Generated by Django 6.0.1 on 2026-02-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ignore_old_task_migrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
