# Generated by Django 6.0.1 on 2026-02-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_projectmilestone_status_and_more'),
        ('tasks', '0002_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.projectmilestone'),
        ),
    ]
