# Generated by Django 6.0.1 on 2026-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned')], max_length=30),
        ),
    ]
