# Generated by Django 6.0.1 on 2026-02-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskfile_taskreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rework', 'Rework')], default='pending', max_length=20),
        ),
    ]
